name: Tests and Coverage
# Make sure only one action triggers the job, otherwise pushing to a
# pull-request will run it twice.
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master
      - rhel10-branch
      - rhel9-branch
      - rhel8-branch
      - rhel7-branch
      - f40-branch
      - f39-branch
      - f38-branch
      - f37-branch
      - f36-branch

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone Repository"
        uses: actions/checkout@v4
      - name: Run lorax tests in podman
        run: make test-in-podman && cp .test-results/.coverage .coverage
      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
